# Generated by Django 2.2.4 on 2019-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
